# Generated by Django 4.1.7 on 2023-03-29 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("-id",),
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
